### ISSUE TITLE
Blocking mode not working

### ISSUE THREAD

**Issue by floodico** [deanpcmad/sidekiq-limit_fetch#95]
my **config.yml**
    
    :concurrency: 10
    :pidfile: tmp/pids/sidekiq.pid
    :queues:
      - promote
      - generate_file
      - extract_metadata
    :blocking:
      - promote

when i run server, i see only **promote** queue is running.  **generate_file** queue is running after next  sidekiq restart. And  **extract_metadata** job executing after yet one sidekiq restart

**Comment by brandoncc** [comment]
I just figured out I am having this problem too. Is this gem dead @brainopia? It looks like you haven't responded to anything in a year and a half.

**Comment by brandoncc** [comment]
I created a sample rails app that matches my setup which has the problem https://github.com/brandoncc/sidekiq-blocking-problem-app

**Comment by deanpcmad** [comment]
Hey, thanks for your issue! I've just taken over this project/gem and am going through the PRs and issues. I see this issue is stale so I'm going to close it but if you are still experiencing issues, please feel free to re-open.

**Comment by banesto** [comment]
gem version: 3.4.0
Sidekiq version: 4.2.10
Rails version: 5.0.7.2
Ruby version: 2.7.6

Still an issue. Blocking essentially takes only blocked queues and don't take less prioritized queue jobs into processing. 

sidekiq.yml
```
:verbose: true
:concurrency: 10

development:
  :concurrency: 10

:queues:
  - top_priority
  - default
  - bottom_priority

:timeout: 30

:blocking:
  - [top_priority,default]

:limits:
  top_priority: 10
  default: 5
  bottom_priority: 10
```

Launching 2 Sidekiq processes:
```
bundle exec sidekiq -q top_priority -q default -q bottom_priority
bundle exec sidekiq -q default -q top_priority -q bottom_priority
```

I've found the problematic place - `lib/sidekiq/limit_fetch/global/selector.rb` `#redis_acquire_script` Lua script:
```
if not blocking_mode then
  blocking_mode = can_block and locks > 0
end
```

This sets `blocking_mode` to `true` because `locks` is always more than `0` and all non-blocking queue are ignored. 
Variable `locks` is evaluated like this `locks = redis.call('llen', probed_key)` - it's not actual counter of jobs enqueued as I assumed but something else. And this queue is never empty - not sure why - it's being refreshed as values are changing during running time of Sidekiq

```
[147] pry(main)> redis.call('lrange', "development:limit_fetch:probed:top_priority", 0, -1)
=> ["b3a8ea7f-8f6d-47be-a996-e15281656f8b",
 "b3a8ea7f-8f6d-47be-a996-e15281656f8b",
 "b3a8ea7f-8f6d-47be-a996-e15281656f8b",
 "b3a8ea7f-8f6d-47be-a996-e15281656f8b",
 "b3a8ea7f-8f6d-47be-a996-e15281656f8b",
 "b3a8ea7f-8f6d-47be-a996-e15281656f8b",
 "b3a8ea7f-8f6d-47be-a996-e15281656f8b",
 "b3a8ea7f-8f6d-47be-a996-e15281656f8b"]
```

Root cause is hard to understand as I cannot find where and when data is pushed onto `..probed:#{queue}` - maybe it's garbage collection failure or wrong destination for probed jobs.

P.S. Tried also newest version of gem & Sidekiq 6 to no success.
